name = "wjl"

[install]
completion = true
quiet = false
optimize = 2

[sysimg]
# incremental = true
# filter_stdlibs = false

[sysimg.precompile]
execution_file = ["deps/precompile.jl"]
# statements_file = ["deps/statements.jl"]

[application]
# default is false, some times error during compilation
# incremental = true
# filter_stdlibs = false
include_lazy_artifacts = true

[application.precompile]
execution_file = ["deps/precompile.jl"]
# statements_file = ["deps/statements.jl"]
